### ISSUE TITLE
Astro MDX example?

### ISSUE THREAD

**Issue by ReinhardtR** [atomiks/rehype-pretty-code#42] opened 2022-09-10 18:49 UTC
Any working example with Astro MDX?

**Comment by davidhu2000** [comment] 2022-09-27 04:51
i managed to get it working https://github.com/davidhu2000/davidhu2000.github.io/pull/52 

there are some issues with it 

- need to disable syntaxHighlight in astro config
- doesn't work on `.mdx` files

**Comment by tanerijun** [comment] 2022-10-15 13:01
> 

Can confirm that it doesn't work with .mdx files. Not sure if it's just Astro though.

**Comment by atomiks** [comment] 2022-10-15 13:33
It works with MDX in Next.js. In the tests, it takes a hAST from the remark parser, then that hAST can be converted into HTML after this plugin has done its work:

https://github.com/atomiks/rehype-pretty-code/blob/17e2856c5abe91eefc0830a8b5f8cab9d13aedb5/test/fixtures.test.js#L20-L24

Is there anything special Astro does with MDX files and Rehype plugins that causes it not to work?

**Comment by atomiks** [comment] 2022-10-15 13:51
Seems to be working fine in [StackBlitz](https://stackblitz.com/edit/github-xzbdac-yw25yv?file=astro.config.mjs,src%2Fcomponents%2FCounter.jsx,src%2Fcomponents%2FTitle.astro,src%2Fpages%2Findex.mdx,src%2Fpages%2Ftest.mdx)

**Comment by tanerijun** [comment] 2022-10-15 14:39
What's not working is the line highlight. I forked the StackBlitz and tweak it to my use case, and surprisingly it works just fine.

After investigating more, I found that the problem is with the version of @astrojs/mdx. I updated it to version 0.11.4 in this fork [StackBlitz](https://stackblitz.com/edit/github-xzbdac-gavz3g?file=src/pages/index.mdx) and it's no longer working.

As you can see, the first line of the code in the mdx version doesn't get the `highlighted` class. But if you go to the `/normalmd`, the `highlighted` class is still there.

**Comment by tanerijun** [comment] 2022-10-15 14:42
Tried it on my project. And yes, the problem is with Astro's mdx integration. Downgrading the version fixed the problem. Thanks

**Comment by atomiks** [comment] 2022-10-15 15:15
If you try increasing each version from my StackBlitz, which is the one that stops working? It might be a good idea to file an issue on the Astro repo, or, if there's a workaround we can do for the implementation, that's also possible

**Comment by tanerijun** [comment] 2022-10-15 15:21
v0.10.0 is when it start breaking. [Change log](https://github.com/withastro/astro/blob/main/packages/integrations/mdx/CHANGELOG.md#0100)

**Comment by atomiks** [comment] 2022-10-15 15:23
Found this: https://github.com/withastro/astro/issues/4447

**Comment by kevinzunigacuellar** [comment] 2022-11-10 22:51
Hello 😇, this issue has been resolved in `mdx@0.11.6`. Thank you for your patience here is a quick reproduction I made in [stackblitz](https://stackblitz.com/edit/github-zra7nk)

**Comment by atomiks** [comment] 2022-11-11 09:17
Great news. I'll close this then.

**Closed by atomiks** 2022-11-11 09:17 UTC
